version: '3'

services:
  algorewards:
    container_name: algorand-rewards
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOME}/.ssh:/root/.ssh:ro
      - ${PWD}:${PWD}:cached
      - /var/run/docker.sock:/var/run/docker.sock